language: node_js
node_js:
  - 10.16.1
  - 12.7.0
cache: npm
script:
  - npm run cover
  - npx codecov
  - cat ./build/coverage/lcov.info | npx coveralls
jobs:
  include:
    - stage: doc
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: 'true'
        script:
          - npx semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email:
    - markus.felten@gmx.de
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
  - npm install -g --production coveralls codecov
after_script:
  - codecov
  - cat ./build/coverage/lcov.info | coveralls
  - npm run docs
after_success:
  - npm run semantic-release
